import { SidebarLayout } from "@/components/layouts/SidebarLayout";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import LoaderProvider from "@/provider/loader-provider";
import { auth } from "@clerk/nextjs/server";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <LoaderProvider>
      {children}
      </LoaderProvider>
  );
}
