import { SidebarLayout } from "@/components/layouts/SidebarLayout";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { auth } from "@clerk/nextjs/server";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { userId, redirectToSignIn } = await auth();
  if (!userId) return redirectToSignIn();

  return (
    <SidebarProvider>
      <SidebarLayout />
      <SidebarTrigger />
      {children}
    </SidebarProvider>
  );
}
